name: Deploy to Kubernetes

on:
  push:
    branches:
      - stage

env:
  AWS_REGION: ***
  ECR_REPOSITORY: ***
  ECR_REGISTRY:****
  K8S_NAMESPACE: snapdeal
  DEPLOYMENT_NAME: snapdeal-app
  K8S_MASTER_IP: ****
  K8S_INTERNAL_IP: ***

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        echo "Installing AWS CLI v2..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION
        aws sts get-caller-identity

    - name: Login to Amazon ECR
      run: |
        echo "Logging into Amazon ECR..."
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build, tag, and push image to Amazon ECR
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Building Docker image..."
        docker build \
          -f laravel-ecommerce/docker/app/Dockerfile.prod \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          laravel-ecommerce
        
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "  Image pushed successfully!"

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y netcat-openbsd dnsutils

    - name: Setup SSH for K8s API tunnel
      env:
        AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
      run: |
        echo "Setting up SSH connection to Kubernetes master..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        echo "$AWS_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        ssh-keyscan -H $K8S_MASTER_IP >> ~/.ssh/known_hosts 2>/dev/null || true
        
        # Test SSH connection
        echo "Testing SSH connection..."
        ssh -o StrictHostKeyChecking=no \
            -o ConnectTimeout=10 \
            -o BatchMode=yes \
            ubuntu@$K8S_MASTER_IP "echo 'SSH connection successful'" || exit 1
        
        echo " SSH setup complete"

    - name: Create SSH tunnel to Kubernetes API
      run: |
        echo "Creating SSH tunnel: localhost:6443 -> $K8S_INTERNAL_IP:6443"
        
        # Kill any existing tunnel
        pkill -f "ssh.*6443" || true
        sleep 2
        
        # Create the tunnel in background
        ssh -o StrictHostKeyChecking=no \
            -o ExitOnForwardFailure=yes \
            -o ConnectTimeout=10 \
            -N -L 127.0.0.1:6443:$K8S_INTERNAL_IP:6443 \
            ubuntu@$K8S_MASTER_IP &
        
        TUNNEL_PID=$!
        echo "Tunnel PID: $TUNNEL_PID"
        
        # Wait for tunnel to establish
        echo "Waiting for tunnel to establish..."
        for i in {1..30}; do
          if nc -z 127.0.0.1 6443 2>/dev/null; then
            echo "  Tunnel established successfully"
            break
          fi
          echo "Attempt $i: Waiting for tunnel..."
          sleep 1
        done
        
        # Verify tunnel
        if ! nc -z 127.0.0.1 6443 2>/dev/null; then
          echo "  Failed to establish tunnel"
          exit 1
        fi

    - name: Install kubectl
      run: |
        echo "Installing kubectl..."
        curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client

    - name: Setup kubeconfig with localhost
      run: |
        mkdir -p ~/.kube
        
        # FIX: Secret should be the raw YAML content, not base64-encoded
        cat > ~/.kube/config << 'KUBECONFIG_EOF'
        ${{ secrets.KUBE_CONFIG }}
        KUBECONFIG_EOF
        
        # Replace the server URL to use localhost
        sed -i 's|https://10\.0\.7\.69:6443|https://127.0.0.1:6443|g' ~/.kube/config
        
        chmod 600 ~/.kube/config
        
        echo "  Kubeconfig configured to use tunnel"
        echo "Server endpoint:"
        grep "server:" ~/.kube/config
        
        # Validate kubeconfig syntax
        echo "Validating kubeconfig..."
        kubectl config view > /dev/null 2>&1
        if [ $? -ne 0 ]; then
          echo "  Invalid kubeconfig"
          cat ~/.kube/config
          exit 1
        fi

    - name: Verify cluster access
      run: |
        echo "Verifying Kubernetes cluster access..."
        
        # Configure to skip TLS verification (since using SSH tunnel)
        kubectl config set-cluster kubernetes --insecure-skip-tls-verify=true
        
        # Debug: Show current context
        echo "Current context:"
        kubectl config current-context
        
        echo "Cluster info:"
        kubectl cluster-info
        
        # Try to get nodes with verbose output
        echo "Attempting to get nodes..."
        kubectl get nodes --request-timeout=30s -v=6 || {
          echo "  Cluster access failed"
          echo "Debugging info:"
          kubectl config view
          kubectl auth can-i list nodes
          exit 1
        }
        
        echo "  Cluster access verified!"

    - name: Update ECR secret in Kubernetes
      run: |
        echo "Refreshing ECR secret in Kubernetes..."
        TOKEN=$(aws ecr get-login-password --region $AWS_REGION)
        
        kubectl delete secret ecr-secret -n $K8S_NAMESPACE --ignore-not-found=true
        kubectl create secret docker-registry ecr-secret \
          --docker-server=$ECR_REGISTRY \
          --docker-username=AWS \
          --docker-password="${TOKEN}" \
          -n $K8S_NAMESPACE
        
        echo "  ECR secret updated"

    - name: Update Kubernetes deployment
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "Updating deployment with new image..."
        echo "Image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        
        kubectl set image deployment/$DEPLOYMENT_NAME \
          $DEPLOYMENT_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          -n $K8S_NAMESPACE
        
        echo "Waiting for rollout..."
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE --timeout=5m
        
        echo "  Deployment successful!"

    - name: Verify deployment
      run: |
        echo "========================================"
        echo "         Deployment Verification        "
        echo "========================================"
        kubectl get deployment $DEPLOYMENT_NAME -n $K8S_NAMESPACE
        kubectl get pods -n $K8S_NAMESPACE -l app=snapdeal-app -o wide
        kubectl get svc snapdeal-app -n $K8S_NAMESPACE
        kubectl get events -n $K8S_NAMESPACE --sort-by='.lastTimestamp' | tail -10

    - name: Rollback on failure
      if: failure()
      run: |
        echo "  Deployment failed! Rolling back..."
        kubectl rollout undo deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE || true
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $K8S_NAMESPACE --timeout=3m || true
        kubectl get pods -n $K8S_NAMESPACE -l app=snapdeal-app -o wide

    - name: Cleanup SSH tunnel
      if: always()
      run: |
        echo "Cleaning up SSH tunnel..."
        pkill -f "ssh.*6443" || true
        echo " Cleanup complete"

    - name: Deployment summary
      if: always()
      run: |
        echo ""
        echo "========================================"
        echo "         Deployment Summary             "
        echo "========================================"
        echo "Status: ${{ job.status }}"
        echo "Image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}"
        echo "Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        echo "========================================" 
