apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-secret-refresh
  namespace: snapdeal
spec:
  schedule: "0 */10 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: ecr-secret-refresher 
          containers:
          - name: refresh
            image: amazonlinux:2
            env:
            - name: AWS_DEFAULT_REGION
              value: xxx
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            command:
            - /bin/bash
            - -c
            - |
              set -e

              yum install -y awscli curl

              curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
              chmod +x kubectl
              mv kubectl /usr/local/bin/

              TOKEN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)

              kubectl create secret docker-registry ecr-secret \
                --docker-server=21xxxx.dkr.ecr.rrr.amazonaws.com \
                --docker-username=AWS \
                --docker-password="$TOKEN" \
                -n snapdeal \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "ECR secret refreshed successfully"
