apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snapdeal-app-hpa
  namespace: snapdeal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snapdeal-app
  minReplicas: 4
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
    scaleUp:
      stabilizationWindowSeconds: 0    # Scale up immediately
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15              # Double pods every 15 seconds if needed
